import datetime
from collections import deque

def create_rota(tasks, people, start_date=None):
    """
    Creates a weekly housework rota.

    Args:
        tasks (list): A list of housework tasks (strings).
        people (list): A list of people to assign tasks to (strings).
        start_date (str, optional): The start date for the rota in 'YYYY-MM-DD' format.
                                     Defaults to the current date.

    Returns:
        dict: A dictionary representing the weekly rota, with dates as keys and
              a dictionary of task assignments as values.
    """
    num_tasks = len(tasks)
    num_people = len(people)
    if num_people == 0:
        return "No people to assign tasks to."

    # Use a deque to easily rotate through the people
    people_cycle = deque(people)

    if start_date:
        try:
            start_date = datetime.datetime.strptime(start_date, '%Y-%m-%d').date()
        except ValueError:
            print("Invalid date format. Using current date.")
            start_date = datetime.date.today()
    else:
        start_date = datetime.date.today()

    rota = {}
    for i in range(7):  # Generate rota for one week
        current_date = start_date + datetime.timedelta(days=i)
        day_rota = {}
        for j in range(num_tasks):
            person_index = (i + j) % num_people
            day_rota[tasks[j]] = people_cycle[person_index]
        rota[current_date.strftime('%Y-%m-%d')] = day_rota

        # Rotate the people for the next day to ensure fairness (can be adjusted)
        people_cycle.rotate(-1)

    return rota

def display_rota(rota):
    """
    Displays the housework rota in a user-friendly format.

    Args:
        rota (dict): The rota dictionary generated by create_rota.
    """
    if isinstance(rota, str):
        print(rota)
        return

    print("\nHousework Rota:\n")
    for date, assignments in rota.items():
        print(f"Date: {date}")
        for task, person in assignments.items():
            print(f"- {task}: {person}")
        print("-" * 20)

if __name__ == "__main__":
    house_tasks = [
        "Washing Dishes",
        "Cleaning Kitchen",
        "Taking out Trash",
        "Sweeping/Vacuuming Floors",
        "Cleaning Bathrooms"
    ]
    household_members = ["Alice", "Bob", "Charlie"]

    start_date_input = input("Enter the start date for the rota (YYYY-MM-DD, leave blank for today): ")
    if start_date_input:
        weekly_rota = create_rota(house_tasks, household_members, start_date_input)
    else:
        weekly_rota = create_rota(house_tasks, household_members)

    display_rota(weekly_rota)